baseURL = 'http://example.org/'
languageCode = 'en-us'
title = '(╯°□°)╯︵ ┻━┻'
theme = 'ananke' 

SectionPagesMenu = "main"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
text_color="red"

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/GoHugoIO"